# this docker file ist deployed on the remote server

version: '3.3'
services:
  postgres-db:
    image: postgres:12.4
    container_name: postgres-db
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - database:/var/lib/
  backend:
    image: backend
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysql
volumes:
  database:
